// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using exchange_simulator.Server.Persistence;

#nullable disable

namespace exchange_simulator.Server.Persistence.Migrations
{
    [DbContext(typeof(ExchangeDbContext))]
    [Migration("20260819135853_InitialTradingWorld")]
    partial class InitialTradingWorld
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.AccountOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashChange")
                        .HasColumnType("numeric");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<long>("InstrumentQuantityChange")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<Guid?>("TradeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SequenceNumber")
                        .IsUnique();

                    b.HasIndex("TradeId");

                    b.HasIndex("AccountId", "SequenceNumber");

                    b.HasIndex("AccountId", "Type")
                        .IsUnique()
                        .HasFilter("\"Type\" IN ('InitialCashGranted', 'InitialInstrumentsGranted')");

                    b.ToTable("AccountOperations", null, t =>
                        {
                            t.HasCheckConstraint("CK_AccountOperations_Payload_Valid", "(\"Type\" = 'InitialCashGranted' AND \"CashChange\" > 0 AND \"InstrumentId\" IS NULL AND \"InstrumentQuantityChange\" = 0 AND \"OrderId\" IS NULL AND \"TradeId\" IS NULL) OR (\"Type\" = 'InitialInstrumentsGranted' AND \"CashChange\" = 0 AND \"InstrumentId\" IS NOT NULL AND \"InstrumentQuantityChange\" > 0 AND \"OrderId\" IS NULL AND \"TradeId\" IS NULL) OR (\"Type\" = 'TradeBuy' AND \"CashChange\" < 0 AND \"InstrumentId\" IS NOT NULL AND \"InstrumentQuantityChange\" > 0 AND \"OrderId\" IS NOT NULL AND \"TradeId\" IS NOT NULL) OR (\"Type\" = 'TradeSell' AND \"CashChange\" > 0 AND \"InstrumentId\" IS NOT NULL AND \"InstrumentQuantityChange\" < 0 AND \"OrderId\" IS NOT NULL AND \"TradeId\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_AccountOperations_SequenceNumber_Positive", "\"SequenceNumber\" > 0");

                            t.HasCheckConstraint("CK_AccountOperations_Type_Valid", "\"Type\" IN ('InitialCashGranted', 'InitialInstrumentsGranted', 'TradeBuy', 'TradeSell')");
                        });
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.BotAccountEntity", b =>
                {
                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.Property<string>("Kind")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.HasKey("WorldId", "Kind");

                    b.HasIndex("AccountId")
                        .IsUnique();

                    b.ToTable("BotAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_BotAccounts_Kind_Valid", "\"Kind\" IN ('MarketMaker', 'NoiseBot')");
                        });
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.InstrumentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InitialPrice")
                        .HasColumnType("numeric");

                    b.Property<long>("LotSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(99)
                        .HasColumnType("character varying(99)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId")
                        .IsUnique();

                    b.ToTable("Instruments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Instruments_InitialPrice_Positive", "\"InitialPrice\" > 0");

                            t.HasCheckConstraint("CK_Instruments_LotSize_Positive", "\"LotSize\" > 0");

                            t.HasCheckConstraint("CK_Instruments_Name_Length", "char_length(\"Name\") BETWEEN 1 AND 99");

                            t.HasCheckConstraint("CK_Instruments_Ticker_Length", "char_length(\"Ticker\") = 4");
                        });
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OwnerAccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.Property<long>("RemainingSize")
                        .HasColumnType("bigint");

                    b.Property<string>("Side")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("Status")
                        .HasFilter("\"Status\" = 'Active'");

                    b.HasIndex("OwnerAccountId", "CreatedAt");

                    b.ToTable("Orders", null, t =>
                        {
                            t.HasCheckConstraint("CK_Orders_Active_IsLimit", "\"Status\" <> 'Active' OR \"Type\" = 'Limit'");

                            t.HasCheckConstraint("CK_Orders_Price_Valid", "(\"Type\" = 'Limit' AND \"Price\" IS NOT NULL AND \"Price\" > 0) OR (\"Type\" = 'Market' AND \"Price\" IS NULL)");

                            t.HasCheckConstraint("CK_Orders_Side_Valid", "\"Side\" IN ('Buy', 'Sell')");

                            t.HasCheckConstraint("CK_Orders_Size_Valid", "\"Size\" > 0 AND \"RemainingSize\" >= 0 AND \"RemainingSize\" <= \"Size\"");

                            t.HasCheckConstraint("CK_Orders_Status_RemainingSize", "(\"Status\" = 'Filled' AND \"RemainingSize\" = 0) OR (\"Status\" IN ('Active', 'Cancelled') AND \"RemainingSize\" > 0)");

                            t.HasCheckConstraint("CK_Orders_Status_Valid", "\"Status\" IN ('Active', 'Filled', 'Cancelled')");

                            t.HasCheckConstraint("CK_Orders_Type_Valid", "\"Type\" IN ('Market', 'Limit')");
                        });
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.OrderHistoryEntryEntity", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<long>("FilledSize")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid");

                    b.Property<long>("RemainingSize")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("TradeId")
                        .HasColumnType("uuid");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("TradeId");

                    b.HasIndex("OrderId", "SequenceNumber");

                    b.ToTable("OrderHistoryEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderHistoryEntries_EventType_Valid", "\"EventType\" IN ('Accepted', 'Activated', 'PartiallyFilled', 'Filled', 'Cancelled')");

                            t.HasCheckConstraint("CK_OrderHistoryEntries_SequenceNumber_Positive", "\"SequenceNumber\" > 0");

                            t.HasCheckConstraint("CK_OrderHistoryEntries_Sizes_NonNegative", "\"FilledSize\" >= 0 AND \"RemainingSize\" >= 0");

                            t.HasCheckConstraint("CK_OrderHistoryEntries_Trade_Valid", "(\"EventType\" IN ('PartiallyFilled', 'Filled') AND \"TradeId\" IS NOT NULL) OR (\"EventType\" IN ('Accepted', 'Activated', 'Cancelled') AND \"TradeId\" IS NULL)");
                        });
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.PositionEntity", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("AveragePrice")
                        .HasColumnType("numeric");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<long>("Quantity")
                        .HasColumnType("bigint");

                    b.Property<long>("ReservedQuantity")
                        .HasColumnType("bigint");

                    b.HasKey("AccountId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("Positions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Positions_AveragePrice_Valid", "(\"Quantity\" = 0 AND \"AveragePrice\" = 0) OR (\"Quantity\" > 0 AND \"AveragePrice\" > 0)");

                            t.HasCheckConstraint("CK_Positions_Quantity_NonNegative", "\"Quantity\" >= 0");

                            t.HasCheckConstraint("CK_Positions_ReservedQuantity_Valid", "\"ReservedQuantity\" >= 0 AND \"ReservedQuantity\" <= \"Quantity\"");
                        });
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.TradeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("BuyOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExecutedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("SellOrderId")
                        .HasColumnType("uuid");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<long>("Size")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BuyOrderId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("SellOrderId");

                    b.HasIndex("SequenceNumber")
                        .IsUnique();

                    b.ToTable("Trades", null, t =>
                        {
                            t.HasCheckConstraint("CK_Trades_DifferentOrders", "\"BuyOrderId\" <> \"SellOrderId\"");

                            t.HasCheckConstraint("CK_Trades_Price_Positive", "\"Price\" > 0");

                            t.HasCheckConstraint("CK_Trades_SequenceNumber_Positive", "\"SequenceNumber\" > 0");

                            t.HasCheckConstraint("CK_Trades_Size_Positive", "\"Size\" > 0");
                        });
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.TradingAccountEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CashBalance")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ReservedCash")
                        .HasColumnType("numeric");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("TradingAccounts", null, t =>
                        {
                            t.HasCheckConstraint("CK_TradingAccounts_CashBalance_NonNegative", "\"CashBalance\" >= 0");

                            t.HasCheckConstraint("CK_TradingAccounts_ReservedCash_Valid", "\"ReservedCash\" >= 0 AND \"ReservedCash\" <= \"CashBalance\"");
                        });
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.TradingWorldEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<decimal>("InitialCashPerAccount")
                        .HasColumnType("numeric");

                    b.Property<long>("InitialInstrumentsPerAccount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("TradingWorlds", null, t =>
                        {
                            t.HasCheckConstraint("CK_TradingWorlds_InitialCashPerAccount_Positive", "\"InitialCashPerAccount\" > 0");

                            t.HasCheckConstraint("CK_TradingWorlds_InitialInstrumentsPerAccount_Positive", "\"InitialInstrumentsPerAccount\" > 0");
                        });
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.AccountOperationEntity", b =>
                {
                    b.HasOne("exchange_simulator.Server.Persistence.Entities.TradingAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("exchange_simulator.Server.Persistence.Entities.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("exchange_simulator.Server.Persistence.Entities.OrderEntity", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("exchange_simulator.Server.Persistence.Entities.TradeEntity", null)
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.BotAccountEntity", b =>
                {
                    b.HasOne("exchange_simulator.Server.Persistence.Entities.TradingAccountEntity", null)
                        .WithOne()
                        .HasForeignKey("exchange_simulator.Server.Persistence.Entities.BotAccountEntity", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("exchange_simulator.Server.Persistence.Entities.TradingWorldEntity", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.InstrumentEntity", b =>
                {
                    b.HasOne("exchange_simulator.Server.Persistence.Entities.TradingWorldEntity", null)
                        .WithOne()
                        .HasForeignKey("exchange_simulator.Server.Persistence.Entities.InstrumentEntity", "WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.OrderEntity", b =>
                {
                    b.HasOne("exchange_simulator.Server.Persistence.Entities.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("exchange_simulator.Server.Persistence.Entities.TradingAccountEntity", null)
                        .WithMany()
                        .HasForeignKey("OwnerAccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.OrderHistoryEntryEntity", b =>
                {
                    b.HasOne("exchange_simulator.Server.Persistence.Entities.OrderEntity", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("exchange_simulator.Server.Persistence.Entities.TradeEntity", null)
                        .WithMany()
                        .HasForeignKey("TradeId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.PositionEntity", b =>
                {
                    b.HasOne("exchange_simulator.Server.Persistence.Entities.TradingAccountEntity", null)
                        .WithOne()
                        .HasForeignKey("exchange_simulator.Server.Persistence.Entities.PositionEntity", "AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("exchange_simulator.Server.Persistence.Entities.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.TradeEntity", b =>
                {
                    b.HasOne("exchange_simulator.Server.Persistence.Entities.OrderEntity", null)
                        .WithMany()
                        .HasForeignKey("BuyOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("exchange_simulator.Server.Persistence.Entities.InstrumentEntity", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("exchange_simulator.Server.Persistence.Entities.OrderEntity", null)
                        .WithMany()
                        .HasForeignKey("SellOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("exchange_simulator.Server.Persistence.Entities.TradingAccountEntity", b =>
                {
                    b.HasOne("exchange_simulator.Server.Persistence.Entities.TradingWorldEntity", null)
                        .WithMany()
                        .HasForeignKey("WorldId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
