<Project Sdk="Microsoft.NET.Sdk">
    
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <RootNamespace>exchange_simulator.Server</RootNamespace>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>
    
    <ItemGroup>
        <ProjectReference Include="..\exchange-simulator\exchange-simulator.csproj" />
        <ProjectReference Include="..\exchange-simulator.Contracts\exchange-simulator.Contracts.csproj" />
    </ItemGroup>
    
</Project>